### Use this file to test out your REST call before implementing them in the code

# Local JSON-Server
### Change the IP address below to your PC's IP address. Remain the port number 3000 unchanged
# @baseUrl = http://192.168.0.5:3000

# Local Firebase Emulator 
@baseUrl = http://192.168.100.40:5001/vaccine8-dcf02/us-central1/api

# Live Firebase
# @baseUrl = https://us-central1-mvvm-frontend-and-mvc-backend.cloudfunctions.net/api

### Request 1 : Get a user whose correct 'login' and 'password'
### Purpose   : To simulate the authentication process. 
GET {{baseUrl}}/medicines?appointmentId=2

### Request 2 : Get the counter data  for a given user
GET {{baseUrl}}/appointments?type=vaccine&applicantId=LHG216ZbBqfw3DpCCtxregwTzjq1

### Request 3 : Update the information of a given counter
PUT {{baseUrl}}/appointments/3
Content-Type: application/json

{
    "centerId": "perdana hospital",
    "applicantId": "LHG216ZbBqfw3DpCCtxregwTzjq1",
    "type": "pcr",
    "day": "2021-07-12 00:00:00.000Z",
    "symptoms": null,
    "reply": null,
    "approve": false,
    "disapprove": true
}

### Request 3 : Update the information of a given counter
POST {{baseUrl}}/appointments
Content-Type: application/json

{
    "centerId": "perdana hospital",
    "applicantId": "LHG216ZbBqfw3DpCCtxregwTzjq1",
    "type": "pcr",
    "day": "2021-07-12 00:00:00.000Z",
    "symptoms": null,
    "reply": null,
    "approve": false,
    "disapprove": true
}


### Request 3 : Update the information of a given counter
PATCH {{baseUrl}}/appointments/3
Content-Type: application/json

{
    "type": "vaccine"
}

### Request: Get all users
GET {{baseUrl}}/centers

### Request: Add a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "login": "user4",
    "password": "123",
    "name": "John Doe",
    "id": "user4"
}

### Request: Delete a user
DELETE {{baseUrl}}/users/M0USorawg6O3xJawA8i7