### Use this file to test out your REST call before implementing them in the code

### Change the IP address below to your PC's IP address. Remain the port number 3000 unchanged
@baseUrl = http://192.168.68.107:3000

### Request 1 : Get a user whose correct 'login' and 'password'
### Purpose   : To simulate the authentication process. 
Get {{baseUrl}}/pcrCenters

### Request 3 : Create a new todo for a given user
PUT {{baseUrl}}/users?id=2
Content-Type: application/json

{
    
    "login": "user3",
    "password": "12345",
  
}
### Request 4 : delte user
GET {{baseUrl}}/Applicant?email=abdalla@gmail.com&password=1234


###
GET {{baseUrl}}/doctors?name=dr.omar&&password=123
###
GET {{baseUrl}}/hospitals
###
GET {{baseUrl}}/doctors?DoctorlId=1
###
GET {{baseUrl}}/Appointments

###

POST {{baseUrl}}/Appointments
Content-Type: application/json

{
    "id":3,
       "time": "14-52-22",
        "hospitalName": "Skudai Hospital",
        "doctorId": 1,
        "userId": 25,
        "day": 0,
        "day": "2021-06-23 00:00:00.000Z"
        ,
        "isSelected": false
}
###

Post {{baseUrl}}/Appointments
Content-Type: application/json

{
   
        "time": "",
        "hospitalName": "",
        "dcotorId": 2,
        "userId": 1,
}

###
GET   {{baseUrl}}/Appointments?DoctorId=1

Content-Type: application/json

{
   
        "name":"dr.abdalla"
}